### ISSUE TITLE
I have re-downloaded KRNL many times from krnl.ca/krnl.place buit it still says my KRNL is outdated. How do i fix this?

### ISSUE THREAD

**Issue by FakeKnifes** [Krnl-staff/FAQ#16]

**Comment by bobinopanino2** [comment]
Me too

**Comment by bobinopanino2** [comment]
It says that your internet is probably blocking the site ?

**Comment by bobinopanino2** [comment]
Now I tried to restart my computer and my router, nothing.

**Comment by FakeKnifes** [comment]
yep it says internet blocking, i tried restarting and using vpn, still doesnt work

**Comment by FakeKnifes** [comment]
even tho it says that, my krnl still pops up, but when i try injecting it says outdated

**Comment by bobinopanino2** [comment]
Good news !

**Comment by bobinopanino2** [comment]
I turned off the computer for 1/2 hour, after I restarted my router and now it works ! (Without VPN)

**Comment by FakeKnifes** [comment]
Igh, i'll try that out rq!
