### ISSUE TITLE
An unexpected error has occurred! Please close the client.

### ISSUE THREAD

**Issue by v1d4s** [Krnl-staff/FAQ#31]
[](url)
![Screenshot 2023-03-25 133138](https://user-images.githubusercontent.com/128902929/227715020-2c57c2d2-4991-44cf-b186-2b9882c6978b.png)
I can't inject KRNL. When I am trying to, the game just crashes.

**Comment by cffddhd** [comment]
i have the same problem and i dont know what to do
i tried everything to fix this error but nothing worked.

**Comment by v1d4s** [comment]
> i have the same problem and i dont know what to do i tried everything to fix this error but nothing worked.

Same bro, I even followed the instructions in KRNL official yt, still nothing changed.

**Comment by cffddhd** [comment]
![image](https://user-images.githubusercontent.com/129077592/228321219-ac3bd268-cea3-4222-93d8-2538749918c2.png)
this is what he replied

**Comment by cffddhd** [comment]
> > У меня та же проблема, и я не знаю, что делать, я попробовал все, чтобы исправить эту ошибку, но ничего не сработало.
> 
> Тот же бро, я даже следовал инструкциям в KRNL official yt, все равно ничего не изменилось.

same

**Comment by cffddhd** [comment]
try on another roblox account
