### ISSUE TITLE
My krnl is stuck on checking version (the injecting part)

### ISSUE THREAD

**Issue by BlaBIa** [Krnl-staff/FAQ#39]
Okay so first my krnl was stuck on the try using a vpn loading screen when and i fixed it by using a vpn by watching a youtube video but now when i try to inject it it jsut gets stuck on the checkin version injection command prompt screen and sometiems it shows me "injecting failed retrying in 3 seconds" or something like that can someone help

**Comment by oogaD** [comment]
Hello @BlaBIa, the error you're describing seems to **already have a solution posted** in [this FAQ](https://github.com/Krnl-staff/FAQ/blob/main/Injection/Connection_Error_Retrying_Error.md)

**As mentioned in the [FAQ above](https://github.com/Krnl-staff/FAQ/blob/main/Injection/Connection_Error_Retrying_Error.md)**, if _none_ of the fixes listed work for you then you're always welcome to ask in our [Discord server](https://krnl.place/invite)
