### ISSUE TITLE
roblox process not found

### ISSUE THREAD

**Issue by mariohany534** [Krnl-staff/FAQ#49]
im using website roblox and its still not working it was working fine now injecting gives me roblox process not found even ingame

**Comment by zeemka** [comment]
You are most likely have Byfron, check how to bypass it in announcements section

**Comment by ganchiru** [comment]
same problem and i already followed the steps provided by discord

**Comment by mariohany534** [comment]
i dont have it it says LIVE and says 32 bit for me
