### ISSUE TITLE
Krnl currently patched, please try again later.

### ISSUE THREAD

**Issue by catalcin** [Krnl-staff/FAQ#52]
Well, when i try to launch krnl on beta or legacy, it says "Krnl currently patched, please try again later." when it is currently working.

![image](https://github.com/Krnl-staff/FAQ/assets/129206689/067532c6-9d10-4582-be68-9e7ff05e1bef)
![image](https://github.com/Krnl-staff/FAQ/assets/129206689/fbb9a834-8cdd-48d5-bd27-67804b2f1fc1)
![image](https://github.com/Krnl-staff/FAQ/assets/129206689/605c6ff0-4bb0-4d8e-a223-f66e89a73373)

**Comment by lamletuti** [comment]
tôi cũng bị
