### ISSUE TITLE
krnl is currently patched please try again later

### ISSUE THREAD

**Issue by hiihihihihihi** [Krnl-staff/FAQ#53]
I dont now but i can't go to the krnl help me!

![2023-09-02_01-53-06](https://github.com/Krnl-staff/FAQ/assets/143845582/473d8d9d-baa8-41e8-b2d9-dafa7f655279)

**Comment by shad0wscr1pt3r** [comment]
i think is patched (It means that its being Detectable in roblox so they are fixing it and they just close his servers to fix it)
